services:
  db:
    image: postgres:17
    container_name: postgres_db

    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: telegram_bot

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  bot:
    build: .
    container_name: telegram_bot

    depends_on:
      - db

    restart: always

volumes:
  postgres_data: